# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/matteozinutti/"
weight = 1

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Toxma"
weight = 2

[social.params]
icon = "brand-github"

[[social]]
identifier = "gitlab"
name = "GitLab"
url = "https://gitlab.com/Toxma"
weight = 3

[social.params]
icon = "brand-gitlab"
